# Generated by Django 4.1.3 on 2022-11-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_main', '0002_alter_product_amount_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=128, verbose_name='商品コード'),
        ),
    ]
