# Generated by Django 4.1.3 on 2022-11-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_main', '0005_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_import', models.FileField(blank=True, upload_to='image_zip')),
            ],
        ),
    ]
