# Generated by Django 4.1.3 on 2022-11-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_main', '0006_imagezip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='価格'),
        ),
    ]
