# Generated by Django 4.1.3 on 2022-11-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_main', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagezip',
            name='zip_import',
            field=models.FileField(blank=True, help_text='※画像のzipファイルをアップロードしてください。', upload_to='image_zip'),
        ),
    ]
