# Generated by Django 4.1.3 on 2022-11-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='address',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='sale',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='郵便番号'),
        ),
    ]
