# Generated by Django 4.1.3 on 2022-11-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sale_address_sale_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product', verbose_name='商品画像'),
        ),
    ]
