# Generated by Django 4.1.3 on 2022-11-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_code_alter_product_image_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
